"use client";
import { useState } from "react";
import { ArrowUpRight, BarChart3, Camera, Check, Eye, FilePlus2, ImagePlus, Search, Upload } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { apartments } from "@/lib/data";

const initial=[{id:"A12",name:"Kalliolinna A12",status:"Published"},{id:"A14",name:"Kalliolinna A14",status:"Ready"},{id:"B24",name:"Asemanvalo B24",status:"Reserved"},{id:"C07",name:"Ruukinranta C07",status:"Draft"}];
const statuses=["Draft","Ready","Published","Reserved","Rented"];

export function AdminDashboard(){
 const[items,setItems]=useState(initial);const[notice,setNotice]=useState("");
 function advance(id:string){setItems(s=>s.map(x=>{if(x.id!==id)return x;const idx=statuses.indexOf(x.status);return{...x,status:statuses[Math.min(idx+1,statuses.length-1)]}}));setNotice("Tila päivitetty demo-näkymässä")}
 return <section className="shell py-10 sm:py-16">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><span className="rounded-full bg-[#fff0d8] px-3 py-2 text-[11px] font-black uppercase tracking-wider text-[#8a5600]">Staff concept / demo</span><h1 className="display mt-5 text-5xl sm:text-6xl">Kohteet ja kysyntä</h1><p className="mt-4 text-[#60758a]">Yksi työtila julkaisuihin, 360°-sisältöön ja palvelun kehittämiseen.</p></div><button onClick={()=>setNotice("Uuden asunnon luonnos luotu")} className="flex items-center gap-2 rounded-full bg-[#0a55df] px-5 py-3 font-black text-white"><FilePlus2 size={18}/>Lisää asunto</button></div>
  {notice&&<div className="mt-6 flex items-center gap-2 rounded-2xl bg-[#e6f6ef] p-4 text-sm font-bold text-[#08715b]" role="status"><Check size={18}/>{notice}</div>}
  <Tabs defaultValue="properties" className="mt-9"><TabsList className="h-12 rounded-full bg-white p-1"><TabsTrigger value="properties" className="rounded-full px-5">Kohteet</TabsTrigger><TabsTrigger value="analytics" className="rounded-full px-5">Analytiikka</TabsTrigger><TabsTrigger value="workflow" className="rounded-full px-5">360° workflow</TabsTrigger></TabsList>
   <TabsContent value="properties"><div className="mt-6 overflow-hidden rounded-[28px] bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e1e8ef] p-5"><div className="flex min-w-[240px] flex-1 items-center gap-3 rounded-xl bg-[#eef3f7] px-4 py-3"><Search size={17}/><input className="w-full bg-transparent outline-none" placeholder="Hae asuntoa tai kohdetta" aria-label="Hae asuntoa"/></div><button className="rounded-xl border px-4 py-3 text-sm font-bold">Suodata</button></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead><tr className="text-xs uppercase tracking-wider text-[#6a7d90]"><th className="p-5">Asunto</th><th className="p-5">Media</th><th className="p-5">Vuokra</th><th className="p-5">Tila</th><th className="p-5">Toiminto</th></tr></thead><tbody>{items.map((x,i)=><tr key={x.id} className="border-t border-[#e7edf2]"><td className="p-5"><div className="flex items-center gap-3"><img src={apartments[i].image} alt="" className="h-12 w-16 rounded-lg object-cover"/><div><b>{x.name}</b><small className="block text-[#687d91]">{apartments[i].area} · {apartments[i].size} m²</small></div></div></td><td className="p-5"><span className="flex items-center gap-2 text-sm font-bold"><Camera size={17} className="text-[#0a55df]"/>{i===3?"Kuvat puuttuvat":"360° valmis"}</span></td><td className="p-5 font-bold">{apartments[i].rent} €</td><td className="p-5"><span className={`rounded-full px-3 py-2 text-xs font-black ${x.status==="Published"?"bg-[#e4f6ee] text-[#08735c]":x.status==="Reserved"?"bg-[#fff0d8] text-[#8a5600]":"bg-[#edf2f6] text-[#526a82]"}`}>{x.status}</span></td><td className="p-5"><button onClick={()=>advance(x.id)} className="rounded-xl border px-3 py-2 text-sm font-bold">Seuraava tila</button></td></tr>)}</tbody></table></div></div></TabsContent>
   <TabsContent value="analytics"><div className="mt-6 grid gap-5 md:grid-cols-3">{[["Suosituin alue","Hyrylä","38 % hauista"],["Keskimääräinen budjetti","860 €","viimeiset 30 pv"],["360°-katselut","1 248","demo-data"],["Hakemuskonversio","Seurattavissa","haku → asunto → hakemus"],["Yleisin asukaskysymys","Vuokra ja maksut","tietopohjainen apuri"],["Suosituin kohde","Kalliolinna","286 kohdesivun avausta"]].map((x,i)=><article key={x[0]} className={`rounded-[26px] p-6 ${i===3?"bg-[#0a55df] text-white":"bg-white"}`}><p className={`text-sm font-bold ${i===3?"text-[#cfe0ff]":"text-[#64788c]"}`}>{x[0]}</p><strong className="mt-5 block text-3xl tracking-[-.04em]">{x[1]}</strong><small className={`mt-2 block ${i===3?"text-[#e1ebff]":"text-[#77899a]"}`}>{x[2]}</small></article>)}</div><div className="mt-5 rounded-[28px] bg-white p-7"><div className="flex items-center justify-between"><div><p className="eyebrow">Asuntohaku-funneli</p><h2 className="mt-3 text-xl font-black">Haku → kohde → hakemus</h2></div><BarChart3 className="text-[#0a55df]"/></div><div className="mt-8 grid gap-5">{[["Hakutulokset",100],["Kohdesivu",64],["360°-kierros",42],["Hakemus",18]].map(([l,v])=><div key={String(l)}><div className="mb-2 flex justify-between text-sm font-bold"><span>{l}</span><span>{v}</span></div><div className="h-3 rounded-full bg-[#e5edf4]"><div className="h-3 rounded-full bg-[#0a55df]" style={{width:`${v}%`}}/></div></div>)}</div></div></TabsContent>
   <TabsContent value="workflow"><div className="mt-6 grid gap-5 lg:grid-cols-3"><article className="rounded-[28px] bg-white p-7"><Upload className="text-[#0a55df]"/><span className="eyebrow mt-8 block">01 / Upload</span><h2 className="mt-3 text-xl font-black">Lisää kuvat</h2><p className="mt-3 leading-7 text-[#60758a]">Pudota kuvat ja 360°-aineisto tai kuvaa tuetulla mobiilityönkululla.</p><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl border py-3 font-bold"><ImagePlus size={18}/>Valitse tiedostot</button></article><article className="rounded-[28px] bg-[#e3effc] p-7"><Camera className="text-[#0a55df]"/><span className="eyebrow mt-8 block">02 / Review</span><h2 className="mt-3 text-xl font-black">Tarkista huoneet</h2><p className="mt-3 leading-7 text-[#60758a]">Nimeä tilat, sijoita hotspotit ja tarkista pohjakartan yhteys.</p><button className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-white py-3 font-bold"><Eye size={18}/>Avaa esikatselu</button></article><article className="rounded-[28px] bg-[#102e4e] p-7 text-white"><ArrowUpRight className="text-[#76b5ff]"/><span className="eyebrow mt-8 block !text-[#8fb9df]">03 / Publish</span><h2 className="mt-3 text-xl font-black">Julkaise kohteelle</h2><p className="mt-3 leading-7 text-[#c3d6e8]">Valmis kierros liittyy asuntoon ja päivittyy asiakassivulle yhdellä toiminnolla.</p><button className="mt-6 w-full rounded-xl bg-white py-3 font-bold text-[#102e4e]">Julkaise 360°-kierros</button></article></div></TabsContent>
  </Tabs>
 </section>
}
