"use client";

import Link from "next/link";
import { ArrowRight, Building2, Layers, Trees, Wifi, Car, KeyRound } from "lucide-react";
import type { Apartment } from "@/lib/data";
import { designFor, roomNames, roomArea } from "@/lib/architecture";
import { useLanguage, type LocalizedText } from "./LanguageProvider";

const translated: Record<string, LocalizedText> = {
  "Huoneistokohtainen ilmanvaihto": {fi:"Huoneistokohtainen ilmanvaihto",en:"Apartment-specific ventilation",sv:"Lägenhetsspecifik ventilation"},
  "Vesikiertoinen lattialämmitys": {fi:"Vesikiertoinen lattialämmitys",en:"Water-based underfloor heating",sv:"Vattenburen golvvärme"},
  "50 Mbit/s laajakaista sisältyy vuokraan": {fi:"50 Mbit/s laajakaista sisältyy vuokraan",en:"50 Mbps broadband included in rent",sv:"50 Mbit/s bredband ingår i hyran"},
  "Savuton kohde": {fi:"Savuton kohde",en:"Smoke-free property",sv:"Rökfritt boende"},
  "Hidas EV-lataus 3,6 kW": {fi:"Hidas EV-lataus 3,6 kW",en:"3.6 kW slow EV charging",sv:"Långsam elbilsladdning 3,6 kW"},
  "iLOQ-lukitus": {fi:"iLOQ-lukitus",en:"iLOQ locking",sv:"iLOQ-låsning"},
  "Lemmikit tervetulleita": {fi:"Lemmikit tervetulleita",en:"Pets welcome",sv:"Husdjur välkomna"},
};

export function HomeDetails({apartment}: {apartment: Apartment}) {
  const {text, locale} = useLanguage();
  const t = (fi:string,en:string,sv:string) => text({fi,en,sv});
  const design = designFor(apartment.id);
  const duplex = design.levels > 1;
  const bedrooms = design.rooms.filter(r=>r.kind === "bedroom").length;
  const number = new Intl.NumberFormat(locale === "en" ? "en-FI" : `${locale}-FI`, {maximumFractionDigits:1});
  const yes = t("Kyllä","Yes","Ja"), no = t("Ei","No","Nej");
  const specs = [
    [t("Talotyyppi","Building type","Hustyp"),t("Rivitalo","Terraced house","Radhus")],
    [t("Osoite","Address","Adress"),apartment.address],
    [t("Asuntotyyppi","Apartment type","Bostadstyp"),apartment.layoutLabel],
    [t("Ilmoitettu huoneistoala","Listed apartment area","Angiven lägenhetsyta"),`${number.format(apartment.size)} m²`],
    [t("Asunnon tasot","Apartment levels","Bostadens våningar"),String(design.levels)],
    [t("Makuuhuoneet","Bedrooms","Sovrum"),String(bedrooms)],
    [t("Oma sauna","Private sauna","Egen bastu"),apartment.sauna ? yes : no],
    [t("Parveke","Balcony","Balkong"),apartment.balcony ? yes : t("Ei · oma terassi","No · private terrace","Nej · egen terrass")],
    [t("Lemmikit","Pets","Husdjur"),apartment.pets ? t("Sallittu demossa","Allowed in the demo","Tillåtna i demon") : no],
    [t("Esteettömyys","Accessibility","Tillgänglighet"),duplex ? t("Sisäportaat tasojen välillä","Internal staircase between floors","Invändig trappa mellan våningarna") : t("Yksi taso · kulkureitti tarkistettava","One level · access route to be verified","Ett plan · tillträdesväg ska kontrolleras")],
    [t("Saatavuus","Availability","Tillgänglighet för uthyrning"),t("Esimerkkikohde · ei reaaliaikaista saatavuutta","Example listing · no live availability","Exempelobjekt · ingen aktuell tillgänglighet")],
  ];
  return <section id="home-details" className="scroll-mt-24 border-t border-[#d8dae5] py-10 sm:py-14">
    <p className="eyebrow">{t("Talo ja asunto","House and apartment","Huset och bostaden")}</p>
    <h2 className="display mt-3 text-3xl sm:text-5xl">{t("Enemmän tietoa kodistasi.","Get to know your home.","Lär känna ditt hem.")}</h2>
    <p className="mt-5 max-w-3xl text-base leading-7 text-[#535873]">{apartment.id === "C09" ? t("C09 on yhden tason kaksio, jossa olohuone ja erillinen makuuhuone avautuvat yhteisestä eteisestä. Keittokomero, vaatehuone ja kylpyhuone tuovat arjen toiminnot lähelle toisiaan. Oleskelu jatkuu omalle terassille.","C09 is a single-level home with a living room and separate bedroom reached from a shared hall. The kitchenette, walk-in storage and bathroom keep everyday essentials close. A private terrace extends the living space.","C09 är en tvåa i ett plan med vardagsrum och separat sovrum från en gemensam hall. Kokvrå, klädkammare och badrum samlar vardagens funktioner. En egen terrass förlänger vistelseytan.") : apartment.id === "E15" ? t("E15 jakaa kodin kahteen tasoon. Alakerran olohuone ja keittiö palvelevat yhteistä arkea. Yläkerran kaksi makuuhuonetta ja kylpyhuone avautuvat aulaan. Kerrokset yhdistää kääntyvä kaksivartinen porras.","E15 separates the home into two levels. The downstairs living room and kitchen serve daily life. Two upstairs bedrooms and the bathroom open onto the hall. A two-flight returning staircase connects the floors.","E15 fördelar hemmet på två plan. Vardagsrum och kök nere samlar vardagen. Två sovrum och badrummet på övervåningen nås från hallen. En tvålopps vändtrappa förbinder våningarna.") : t("F20 on kolmella makuuhuoneella varustettu kaksitasoinen perhekoti. Alakerrassa ovat olohuone, keittiö, eteinen ja kylpyhuone. Yläkerran yhteinen aula johtaa jokaiseen makuuhuoneeseen ilman läpikulkua muiden huoneiden kautta.","F20 is a two-level family home with three bedrooms. Downstairs are the living room, kitchen, entrance and bathroom. The shared upper hall leads directly to each bedroom without passing through another room.","F20 är ett familjehem i två plan med tre sovrum. Nere finns vardagsrum, kök, entré och badrum. Den gemensamma hallen uppe leder direkt till varje sovrum utan genomgångsrum.")}</p>
    <p className="mt-3 text-sm leading-6 text-[#62677f]">{t("Varusteet ja tekniset tiedot kuvaavat demoa. Ajantasaiset tiedot vahvistetaan Tuuma Koditilta ennen hakemista.","Equipment and technical details describe the demo. Confirm current property information with Tuuma Kodit before applying.","Utrustning och tekniska uppgifter beskriver demon. Bekräfta aktuella uppgifter med Tuuma Kodit före ansökan.")}</p>
    <div className="mt-8 grid gap-6 lg:grid-cols-2">
      <article className="rounded-2xl border border-[#d8dae5] p-5 sm:p-7"><Building2 size={24}/><h3 className="mt-3 text-xl font-extrabold">{t("Asunnon perustiedot","Apartment facts","Grunduppgifter")}</h3><dl className="mt-5 divide-y divide-[#e5e6ed]">{specs.map(([label,value])=><div key={label} className="grid grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)] gap-4 py-3 text-sm leading-6"><dt className="text-[#62677f]">{label}</dt><dd className="font-semibold">{value}</dd></div>)}</dl></article>
      <div className="space-y-6"><article className="rounded-2xl bg-[#f1f2fa] p-5 sm:p-7"><Wifi size={24}/><h3 className="mt-3 text-xl font-extrabold">{t("Tekniikka ja varustelu","Building systems and equipment","Teknik och utrustning")}</h3><ul className="mt-5 space-y-3 text-base leading-6">{apartment.standards.map(item=><li key={item} className="flex gap-3"><span aria-hidden className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[#3d4785]"/>{text(translated[item] ?? {fi:item,en:item,sv:item})}</li>)}</ul><p className="mt-5 text-sm leading-6 text-[#62677f]">{t("Internetliittymän nopeus, vesimaksu ja sähkösopimus tarkistetaan asuntokohtaisesti. Laskurissa näet kulut eriteltyinä.","Confirm broadband speed, water charges and electricity arrangements for the individual home. The calculator separates these costs.","Kontrollera bredbandshastighet, vattenavgift och elavtal för den enskilda bostaden. Kalkylatorn specificerar kostnaderna.")}</p><Link href={`/kustannukset?asunto=${apartment.id}`} className="mt-4 inline-flex min-h-11 items-center gap-2 font-bold underline underline-offset-4">{t("Avaa kululaskuri","Open cost calculator","Öppna kostnadskalkylatorn")}<ArrowRight size={17}/></Link></article>
      <article className="rounded-2xl border border-[#d8dae5] p-5 sm:p-7"><Car size={24}/><h3 className="mt-3 text-xl font-extrabold">{t("Pysäköinti ja liikkuminen","Parking and getting around","Parkering och resor")}</h3><p className="mt-4 text-base leading-7">{apartment.parking ? t("Autopaikka on mukana kohteen demo-palveluissa. Paikan saatavuus, sijainti ja kuukausimaksu vahvistetaan erikseen.","Parking is included in the property's demo services. Space availability, location and monthly cost are confirmed separately.","Bilplats ingår i objektets demotjänster. Tillgång, läge och månadsavgift bekräftas separat.") : t("Autopaikkaa ei ole merkitty demoon.","No parking is listed in this demo.","Ingen bilplats anges i demon.")}</p><p className="mt-3 text-sm leading-6 text-[#62677f]">{apartment.ev ? t("Sähköauton lataus on valittavissa demossa; paikkakohtainen teho ja hinnoittelu tarkistetaan varauksen yhteydessä.","EV charging is selectable in the demo; confirm charger capacity and pricing when reserving.","Elbilsladdning kan väljas i demon; kontrollera effekt och pris vid bokning.") : t("Ei latauspaikkaa demossa.","No EV charging in the demo.","Ingen elbilsladdning i demon.")}</p></article></div>
    </div>
    <div className="mt-6 grid gap-6 lg:grid-cols-2">
      <article className="rounded-2xl border border-[#d8dae5] p-5 sm:p-7"><Layers size={24}/><h3 className="mt-3 text-xl font-extrabold">{t("Huoneet ja pinta-alat","Rooms and areas","Rum och ytor")}</h3><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">{t("Tilamallin huoneluettelo","Spatial model room schedule","Rumsförteckning för modellen")}</caption><thead><tr className="border-b border-[#d8dae5] text-[#62677f]"><th scope="col" className="pb-3">{t("Huone","Room","Rum")}</th><th scope="col" className="pb-3">{t("Taso","Level","Plan")}</th><th scope="col" className="pb-3 text-right">m²*</th></tr></thead><tbody>{design.rooms.map(room=><tr key={room.id} className="border-b border-[#eeeff5]"><th scope="row" className="py-3 pr-2 font-medium">{room.code} · {room.code === "PORRAS" ? t("Porras","Staircase","Trappa") : text(roomNames[room.kind])}</th><td>{room.level ?? 1}</td><td className="text-right tabular-nums">{number.format(roomArea(room))}</td></tr>)}</tbody></table></div><p className="mt-4 text-sm leading-6 text-[#62677f]">{t("* Konseptimallin suuntaa-antavat huonealat. Ne eivät ole virallisia mittaustietoja eivätkä vastaa suoraan ilmoitettua huoneistoalaa.","* Approximate room areas from the concept model. These are not official measurements and do not directly correspond to the listed apartment area.","* Ungefärliga rumsytor från konceptmodellen. De är inte officiella mätningar och motsvarar inte direkt den angivna lägenhetsytan.")}</p></article>
      <article className="rounded-2xl bg-[#fff4d9] p-5 sm:p-7"><KeyRound size={24}/><h3 className="mt-3 text-xl font-extrabold">{t("Pinnat, säilytys ja kalustus","Finishes, storage and furnishing","Ytor, förvaring och möblering")}</h3><div className="mt-5 space-y-5 text-base leading-7">{[
        [t("Oleskelu ja makuuhuoneet","Living rooms and bedrooms","Vardagsrum och sovrum"),t("Tammilattian tekstuuri, vaaleat seinäpinnat ja kiinteät säilytyskaapit.","Oak floor texture, light walls and fixed storage cabinets.","Ektextur på golvet, ljusa väggar och fasta förvaringsskåp.")],
        [t("Keittiö ja märkätila","Kitchen and wet room","Kök och våtrum"),t("Kiinteät keittiökaapit, työtaso, allas ja liesi. Kylpyhuoneessa laattapinnat, suihku, WC ja pesuallas.","Fixed kitchen cabinets, worktop, sink and hob. Tiled bathroom surfaces with a shower, toilet and basin.","Fasta köksskåp, arbetsbänk, diskho och spishäll. Kakel i badrummet med dusch, toalett och handfat.")],
        [t("Tyhjä vai kalustettu?","Empty or furnished?","Tomt eller möblerat?"),t("Pohja, 3D ja kierros avautuvat tyhjinä. Kalustettu-tila lisää irtokalusteet samaan asuntoon. Keittiö, kaapit, portaat ja saniteettivarusteet säilyvät molemmissa tiloissa.","The plan, 3D model and tour open empty. Furnished mode adds movable furniture to the same apartment. Kitchen, cabinets, stairs and sanitary fittings remain in both modes.","Plan, 3D och rundtur öppnas tomma. Möblerat läge lägger till lösa möbler i samma bostad. Kök, skåp, trappor och sanitetsutrustning finns kvar i båda lägena.")],
      ].map(([title,body])=><div key={title}><h4 className="font-bold">{title}</h4><p className="mt-1 text-[#535873]">{body}</p></div>)}</div></article>
    </div>
    <article className="mt-6 grid overflow-hidden rounded-2xl border border-[#d8dae5] md:grid-cols-2"><img src="/art/tuusula-editorial-area.webp" width="1536" height="1024" loading="lazy" alt={t("Tuusulan alueen konseptikuvitus","Tuusula neighbourhood concept illustration","Konceptillustration av Tusbyområdet")} className="h-full max-h-96 w-full object-cover"/><div className="p-5 sm:p-8"><Trees size={24}/><h3 className="mt-3 text-2xl font-extrabold">{t("Piha ja elämä Hyrylässä","The courtyard and life in Hyrylä","Gården och livet i Hyrylä")}</h3><p className="mt-4 text-base leading-7 text-[#535873]">{t("Oma terassi täydentää kodin oleskelutilaa. Tutustu myös Hyrylän palveluihin, kouluihin, päiväkoteihin ja ulkoilumahdollisuuksiin alue-esittelyssä. Kulkureitit ja palvelujen etäisyydet tarkistetaan ennen oikean kohteen julkaisua.","A private terrace extends the living space. Explore Hyrylä's services, schools, day care and outdoor activities in the area guide. Routes and distances are verified before a real property is published.","En egen terrass förlänger bostadens vistelseyta. Utforska Hyryläs service, skolor, daghem och friluftsmöjligheter i områdesguiden. Rutter och avstånd kontrolleras före publicering av ett verkligt objekt.")}</p><Link href="/alueet" className="mt-5 inline-flex min-h-11 items-center gap-2 font-bold underline underline-offset-4">{t("Tutustu alueeseen","Explore the area","Utforska området")}<ArrowRight size={17}/></Link></div></article>
  </section>;
}
