"use client";
import {useState} from 'react';
import Link from 'next/link';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import {apartments} from '@/lib/data';
import {ApartmentGallery} from './ApartmentGallery';
import {ApartmentPlan} from './ApartmentPlan';
import dynamic from 'next/dynamic';
const Tour = dynamic(() => import('./Tour360Viewer'), {ssr:false});
const Model = dynamic(() => import('./ApartmentDollhouse'), {ssr:false});

const titles=['Tuuma Next','Nykyiset palvelut säilyvät','Kolme esimerkkikotia','Kalustuksen vertailu','Tilat ymmärrettäviksi','Asukkaan ja henkilöstön näkymät','Hyödyt arvioidaan pilotissa','Demo ja seuraava vaihe'];
export function Presentation(){
 const [slide,setSlide]=useState(0),[home,setHome]=useState('C09'),[view,setView]=useState<'tour'|'plan'|'model'>('tour'); const reduced=useReducedMotion();const apartment=apartments.find(a=>a.id===home)!;
 return <main id="main" lang="fi" className="shell py-8 sm:py-12"><div className="mb-7 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold text-[#62677f]">ESITTELY · 14.9.2026 · CONCEPT / DEMO</p><a className="min-h-11 py-3 text-sm font-semibold underline" href="/presentation/tuuma-next-esittely.pdf" download>Lataa PDF-esittely</a></div>
 <div className="mb-6 flex items-center justify-between gap-4"><button className="min-h-11 rounded-full border px-5 disabled:opacity-40" disabled={slide===0} onClick={()=>setSlide(slide-1)}>Edellinen</button><p aria-live="polite" className="text-sm tabular-nums">{slide+1} / {titles.length}</p><button className="min-h-11 rounded-full bg-[#22264b] px-5 text-white disabled:opacity-40" disabled={slide===titles.length-1} onClick={()=>setSlide(slide+1)}>Seuraava</button></div>
 <AnimatePresence mode="wait"><motion.section key={slide} initial={{opacity:reduced?1:0,y:reduced?0:12}} animate={{opacity:1,y:0}} exit={{opacity:reduced?1:0}} transition={{duration:.22}} className="min-h-[60vh] border-t border-[#d8dae5] pt-8"><h1 className="display mb-6 text-4xl sm:text-6xl">{titles[slide]}</h1>
 {slide===0&&<div className="grid items-center gap-8 lg:grid-cols-2"><div><p className="text-xl leading-8">Asiakkaan digitaalinen palvelu Tampuurin ja eTampuurin rinnalle.</p><p className="mt-6 leading-7 text-[#62677f]">Tässä kehitysdemossa voi etsiä kotia, tutkia konseptiasuntoja ja kokeilla asukkaan sekä henkilöstön näkymiä.</p><p className="mt-6 border-l-4 border-[#ffbb18] pl-4 text-sm leading-6">Kolmen konseptiasunnon 25 katselupistettä: vaihda tyhjän ja kalustetun näkymän välillä, kierrä huoneita ja tutki pohjaa. Tuuma Kodit ei ole hyväksynyt konseptia viralliseksi palvelukseen.</p></div><img src="/panoramas/C09/oh-furnished-gallery.webp" alt="C09:n olohuoneen renderöity konseptikuva" width="1536" height="1024" className="rounded-2xl"/></div>}
 {slide===1&&<><p className="mb-7 max-w-3xl text-xl leading-8">Tuuma Kodit tarjoaa jo asuntohaun, hakemuksen, huoltopyynnöt ja eTampuurin asukassivut. Konsepti kokoaa asiakkaan polkua niiden ympärille.</p><div className="overflow-x-auto"><table className="w-full text-left text-base"><thead><tr className="border-b"><th className="p-4">Nykyinen palvelu</th><th className="p-4">Demon lisäys</th></tr></thead><tbody>{[['Asuntohaku ja hakemus','Ohjattu sopivuushaku, suosikit ja vertailu'],['Kohteen tiedot ja kuvagalleria','Huoneiden kuvaparit, 360°-kierros ja pyöritettävä konseptipohja'],['Asukasohjeet ja eTampuuri','Tehtävien mukaan ryhmitelty apu ja demoroolit']].map(row=><tr key={row[0]} className="border-b"><td className="p-4">{row[0]}</td><td className="p-4">{row[1]}</td></tr>)}</tbody></table></div><p className="mt-6 text-sm">Lähteet: <a className="underline" href="https://tuumakodit.fi/" target="_blank" rel="noreferrer">tuumakodit.fi</a> ja <a className="underline" href="https://tuumakodit.fi/kalliolinna/" target="_blank" rel="noreferrer">Kalliolinna</a>, tarkistettu 14.9.2026. Vertailu koskee tarkastettuja julkisia sivuja.</p></>}
 {slide===2&&<><p className="mb-6 text-lg">Julkiset asuntotyypit ja koot. Huonejako, kalustus ja kuvat ovat konseptisuunnittelua.</p><div className="grid gap-6 md:grid-cols-3">{apartments.filter(a=>['C09','E15','F20'].includes(a.id)).map(a=><Link key={a.id} href={`/kohteet/kalliolinna?asunto=${a.id}`} className="group"><img src={a.image} alt={`${a.id}: konseptikuva`} width="1536" height="1024" className="rounded-xl"/><h2 className="mt-4 text-2xl font-bold">{a.id}</h2><p className="mt-2">{a.layoutLabel} · {a.size.toString().replace('.',',')} m² · {a.levels} tasoa</p><p className="mt-3 underline">Avaa asunto</p></Link>)}</div><p className="mt-6 text-sm text-[#62677f]">Vuokrat ovat esimerkkihintoja. Näkymä ei ilmoita tämänhetkistä saatavuutta.</p></>}
 {(slide===3||slide===4)&&<><div role="group" aria-label="Esimerkkiasunto" className="mb-6 flex gap-2">{['C09','E15','F20'].map(id=><button key={id} aria-pressed={home===id} onClick={()=>setHome(id)} className={`min-h-11 rounded-full border px-6 ${home===id?'bg-[#22264b] text-white':''}`}>{id}</button>)}</div>{slide===3?<><p className="mb-6 text-sm leading-6 text-[#62677f]">Jokaisessa katselupisteessä on tyhjä ja kalustettu vaihtoehto. Kamerapaikka, tilat ja valaistus pysyvät samoina. Kokeile myös Vertaa-liukusäädintä. Galleriakuvat ovat samoista panoraamoista rajattuja näkymiä.</p><ApartmentGallery key={home} apartment={apartment}/></>:<><p className="mb-6 text-sm leading-6 text-[#62677f]">360° avautuu tyhjänä. Vedä näkymää ja siirry ovipainikkeista seuraavaan huoneeseen. Pohja ja pyöritettävä 3D-malli täydentävät tilan hahmottamista. Kaikki kolme ovat konseptivisualisointeja.</p><div className="mb-4 flex gap-2" role="group" aria-label="Tilojen esitystapa">{(["tour","plan","model"] as const).map(mode=><button key={mode} onClick={()=>setView(mode)} aria-pressed={view===mode} className={`min-h-11 rounded-full border px-5 ${view===mode?"bg-[#22264b] text-white":""}`}>{mode==="tour"?"360°":mode==="plan"?"Pohja":"3D"}</button>)}</div>{view==="tour"?<Tour key={home} apartment={apartment}/>:view==="model"?<Model key={home} apartment={apartment}/>:<ApartmentPlan key={home} initialApartment={home}/>}</>}</>}
 {slide===5&&<div className="grid gap-12 md:grid-cols-2"><div><h2 className="text-2xl font-bold">OmaKoti</h2><p className="mt-4 text-lg leading-8">Asukkaan esimerkkitiedot kokoavat asumisen asiat yhteen näkymään. Sisäänkirjautuminen ja uloskirjautuminen toimivat demossa.</p><p className="mt-5 font-mono">user / 1234</p><Link href="/oma-koti" className="mt-5 inline-flex min-h-11 items-center font-bold underline">Kokeile asukkaan demoa</Link></div><div><h2 className="text-2xl font-bold">Henkilöstö</h2><p className="mt-4 text-lg leading-8">Julkaisutilojen kokeilu näyttää työnkulun luonnoksesta julkaisuun. Analytiikan luvut ovat synteettisiä esimerkkejä.</p><p className="mt-5 font-mono">admin / 1234</p><Link href="/demo-admin" className="mt-5 inline-flex min-h-11 items-center font-bold underline">Kokeile henkilöstön demoa</Link></div><p className="md:col-span-2 border-t pt-5 text-sm leading-6">Demoroolit eivät suojaa oikeita henkilötietoja. Pankkitunnistautuminen ja Tampuuri-rajapintojen tuotantoyhteydet kuuluvat myöhempään toteutukseen.</p></div>}
 {slide===6&&<><p className="max-w-3xl text-xl leading-8">Tavoitteena on helpompi asiointi ja vähemmän toistuvaa selvitystyötä. Vaikutukset tarvitsevat pilotin.</p><dl className="mt-8 max-w-4xl space-y-6">{[['Asunnon valinta','Seurataan haun, vertailun ja hakemuksen aloituksen etenemistä.'],['Asukaspalvelu','Mitataan yleisten kysymysten määrä ja ohjeen löytämiseen kuluva aika.'],['Kohteen julkaisu','Verrataan työntekijän käyttämää aikaa ennen uutta työnkulkua ja sen jälkeen.']].map(([a,b])=><div key={a} className="border-b pb-5"><dt className="text-xl font-bold">{a}</dt><dd className="mt-2 text-lg text-[#62677f]">{b}</dd></div>)}</dl><p className="mt-7 text-sm">Tässä esityksessä ei luvata prosentuaalista säästöä tai konversion kasvua.</p></>}
 {slide===7&&<><p className="max-w-3xl text-xl leading-8">Kokeiltava kokonaisuus kodin etsinnästä asuntoon tutustumiseen ja asumisen asiointiin.</p><p className="mt-6 max-w-3xl text-lg leading-8">C09, E15 ja F20 sisältävät yhteensä 25 katselupistettä ja 50 renderöityä 360°-näkymää. Kierros ja kuvagalleria näyttävät saman konseptitilan. Asuntosivuilta löytyvät myös pohja ja pyöritettävä 3D-malli.</p><p className="mt-6 max-w-3xl text-lg leading-8">Ennen tuotantokäyttöä vahvistetaan aidot kohdetiedot ja kuvat, tunnistautuminen, tietosuoja sekä yhteydet Tampuuriin. Pilotti selvittää, auttaako kokonaisuus asiakkaita ja henkilöstöä käytännössä.</p><Link href="/" className="showcase-primary mt-8 inline-flex px-6">Kokeile demoa</Link><p className="mt-6 text-sm text-[#62677f]">Itsenäinen konseptidemo. Esimerkkivuokrat ja demoroolien tiedot eivät ole todellisia tarjouksia tai asiakastietoja.</p></>}
 </motion.section></AnimatePresence></main>;
}
