"use client";
import {useState} from 'react';
import Link from 'next/link';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import {apartments} from '@/lib/data';
import {ApartmentGallery} from './ApartmentGallery';
import {ApartmentPlan} from './ApartmentPlan';

const titles=['Tuuma Next','Nykyiset palvelut säilyvät','Kolme esimerkkikotia','Kalustuksen vertailu','Tilat ymmärrettäviksi','Asukkaan ja henkilöstön näkymät','Hyödyt arvioidaan pilotissa','Seuraava laatutarkistus'];
export function Presentation(){
 const [slide,setSlide]=useState(0),[home,setHome]=useState('C09'); const reduced=useReducedMotion();const apartment=apartments.find(a=>a.id===home)!;
 return <main id="main" lang="fi" className="shell py-8 sm:py-12"><div className="mb-7 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold text-[#62677f]">ESITTELYLUONNOS · 14.9.2026 · CONCEPT / DEMO</p><a className="min-h-11 py-3 text-sm font-semibold underline" href="/presentation/tuuma-next-esittelyluonnos.pdf" download>Lataa PDF-luonnos</a></div>
 <div className="mb-6 flex items-center justify-between gap-4"><button className="min-h-11 rounded-full border px-5 disabled:opacity-40" disabled={slide===0} onClick={()=>setSlide(slide-1)}>Edellinen</button><p aria-live="polite" className="text-sm tabular-nums">{slide+1} / {titles.length}</p><button className="min-h-11 rounded-full bg-[#22264b] px-5 text-white disabled:opacity-40" disabled={slide===titles.length-1} onClick={()=>setSlide(slide+1)}>Seuraava</button></div>
 <AnimatePresence mode="wait"><motion.section key={slide} initial={{opacity:reduced?1:0,y:reduced?0:12}} animate={{opacity:1,y:0}} exit={{opacity:reduced?1:0}} transition={{duration:.22}} className="min-h-[60vh] border-t border-[#d8dae5] pt-8"><h1 className="display mb-6 text-4xl sm:text-6xl">{titles[slide]}</h1>
 {slide===0&&<div className="grid items-center gap-8 lg:grid-cols-2"><div><p className="text-xl leading-8">Asiakkaan digitaalinen palvelu Tampuurin ja eTampuurin rinnalle.</p><p className="mt-6 leading-7 text-[#62677f]">Tässä kehitysdemossa voi etsiä kotia, tutkia konseptiasuntoja ja kokeilla asukkaan sekä henkilöstön näkymiä.</p><p className="mt-6 border-l-4 border-[#ffbb18] pl-4 text-sm leading-6">Fotopanoraamakierros ja kaikkien huoneiden kuvaparit ovat vielä kesken. Tämä luonnos esittelee nykyisen demon. Tuuma Kodit ei ole hyväksynyt konseptia viralliseksi palvelukseen.</p></div><img src="/art/kalliolinna-c09-exterior.webp" alt="C09:n julkisivun konseptivisualisointi" width="1536" height="1024" className="rounded-2xl"/></div>}
 {slide===1&&<><p className="mb-7 max-w-3xl text-xl leading-8">Tuuma Kodit tarjoaa jo asuntohaun, hakemuksen, huoltopyynnöt ja eTampuurin asukassivut. Konsepti kokoaa asiakkaan polkua niiden ympärille.</p><div className="overflow-x-auto"><table className="w-full text-left text-base"><thead><tr className="border-b"><th className="p-4">Nykyinen palvelu</th><th className="p-4">Demon lisäys</th></tr></thead><tbody>{[['Asuntohaku ja hakemus','Ohjattu sopivuushaku, suosikit ja vertailu'],['Kohteen tiedot ja kuvagalleria','Kuvaparit sekä pyöritettävä konseptipohja'],['Asukasohjeet ja eTampuuri','Tehtävien mukaan ryhmitelty apu ja demoroolit']].map(row=><tr key={row[0]} className="border-b"><td className="p-4">{row[0]}</td><td className="p-4">{row[1]}</td></tr>)}</tbody></table></div><p className="mt-6 text-sm">Lähteet: <a className="underline" href="https://tuumakodit.fi/" target="_blank" rel="noreferrer">tuumakodit.fi</a> ja <a className="underline" href="https://tuumakodit.fi/kalliolinna/" target="_blank" rel="noreferrer">Kalliolinna</a>, tarkistettu 14.9.2026. Vertailu koskee tarkastettuja julkisia sivuja.</p></>}
 {slide===2&&<><p className="mb-6 text-lg">Julkiset asuntotyypit ja koot. Huonejako, kalustus ja kuvat ovat konseptisuunnittelua.</p><div className="grid gap-6 md:grid-cols-3">{apartments.filter(a=>['C09','E15','F20'].includes(a.id)).map(a=><Link key={a.id} href={`/kohteet/kalliolinna?asunto=${a.id}`} className="group"><img src={a.image} alt={`${a.id}: konseptikuva`} width="1536" height="1024" className="rounded-xl"/><h2 className="mt-4 text-2xl font-bold">{a.id}</h2><p className="mt-2">{a.layoutLabel} · {a.size.toString().replace('.',',')} m² · {a.levels} tasoa</p><p className="mt-3 underline">Avaa asunto</p></Link>)}</div><p className="mt-6 text-sm text-[#62677f]">Vuokrat ovat esimerkkihintoja. Näkymä ei ilmoita tämänhetkistä saatavuutta.</p></>}
 {(slide===3||slide===4)&&<><div role="group" aria-label="Esimerkkiasunto" className="mb-6 flex gap-2">{['C09','E15','F20'].map(id=><button key={id} aria-pressed={home===id} onClick={()=>setHome(id)} className={`min-h-11 rounded-full border px-6 ${home===id?'bg-[#22264b] text-white':''}`}>{id}</button>)}</div>{slide===3?<><p className="mb-6 text-sm leading-6 text-[#62677f]">Olohuoneessa voi vaihtaa tyhjän ja kalustetun kuvan välillä. Muut huoneet eivät vielä muodosta kattavaa kuvaparisarjaa. Kuvat eivät ole 360°-panoraamoja.</p><ApartmentGallery key={home} apartment={apartment}/></>:<><p className="mb-6 text-sm leading-6 text-[#62677f]">Konseptipohja avautuu tyhjänä. Asuntosivun 3D-välilehti tarjoaa pyöritettävän mallin WebGL-yhteensopivalla laitteella. Piirustus ei ole rakennuslupa- tai toteutusasiakirja.</p><ApartmentPlan key={home} initialApartment={home}/></>}</>}
 {slide===5&&<div className="grid gap-12 md:grid-cols-2"><div><h2 className="text-2xl font-bold">OmaKoti</h2><p className="mt-4 text-lg leading-8">Asukkaan esimerkkitiedot kokoavat asumisen asiat yhteen näkymään. Sisäänkirjautuminen ja uloskirjautuminen toimivat demossa.</p><p className="mt-5 font-mono">user / 1234</p><Link href="/oma-koti" className="mt-5 inline-flex min-h-11 items-center font-bold underline">Kokeile asukkaan demoa</Link></div><div><h2 className="text-2xl font-bold">Henkilöstö</h2><p className="mt-4 text-lg leading-8">Julkaisutilojen kokeilu näyttää työnkulun luonnoksesta julkaisuun. Analytiikan luvut ovat synteettisiä esimerkkejä.</p><p className="mt-5 font-mono">admin / 1234</p><Link href="/demo-admin" className="mt-5 inline-flex min-h-11 items-center font-bold underline">Kokeile henkilöstön demoa</Link></div><p className="md:col-span-2 border-t pt-5 text-sm leading-6">Demoroolit eivät suojaa oikeita henkilötietoja. Pankkitunnistautuminen ja Tampuuri-rajapintojen tuotantoyhteydet kuuluvat myöhempään toteutukseen.</p></div>}
 {slide===6&&<><p className="max-w-3xl text-xl leading-8">Tavoitteena on helpompi asiointi ja vähemmän toistuvaa selvitystyötä. Vaikutukset tarvitsevat pilotin.</p><dl className="mt-8 max-w-4xl space-y-6">{[['Asunnon valinta','Seurataan haun, vertailun ja hakemuksen aloituksen etenemistä.'],['Asukaspalvelu','Mitataan yleisten kysymysten määrä ja ohjeen löytämiseen kuluva aika.'],['Kohteen julkaisu','Verrataan työntekijän käyttämää aikaa ennen uutta työnkulkua ja sen jälkeen.']].map(([a,b])=><div key={a} className="border-b pb-5"><dt className="text-xl font-bold">{a}</dt><dd className="mt-2 text-lg text-[#62677f]">{b}</dd></div>)}</dl><p className="mt-7 text-sm">Tässä esityksessä ei luvata prosentuaalista säästöä tai konversion kasvua.</p></>}
 {slide===7&&<><p className="max-w-3xl text-xl leading-8">Hyväksyttävä 360°-kuva tarvitsee yhtenäisen huonegeometrian ja saumattoman palloprojektion.</p><p className="mt-6 max-w-3xl text-lg leading-8">Ensimmäinen generoitu pari oli 1774 × 887 pikseliä. Se ei läpäissyt geometrian ja saumojen tarkistusta. Sitä ei julkaistu asuntojen kierroksena.</p><p className="mt-6 max-w-3xl text-lg leading-8">Seuraava vaihe on laadukas renderöinti samasta tilamallista tai oikea 360°-kuvaus. Tyhjä ja kalustettu versio käyttävät samaa kameraa ja huonerakennetta.</p><Link href="/" className="showcase-primary mt-8 inline-flex px-6">Avaa nykyinen demo</Link><p className="mt-6 text-sm text-[#62677f]">Lopullinen esitys valmistuu hyväksytyn kuvamateriaalin ja laitetestauksen jälkeen.</p></>}
 </motion.section></AnimatePresence></main>;
}
